# IBM DB2 Database Configuration
# Configuration for demographic data assets with multiple source tables

database:
  host: "db"
  port: 50000
  database_name: "DEVDB"
  schema: "SAIL"
  connection:
    driver: "DB2"
    uid: "${DB_USER}"
    pwd: "${DB_PASSWORD}"

# Asset Definitions
# Each asset can have multiple source tables
# Users can select preferred tables per project

assets:
  
  # =========================================================================
  # DATE OF BIRTH ASSET
  # =========================================================================
  date_of_birth:
    description: "Patient date of birth information"
    default_source: "gp_dob"  # Default table to use if not specified
    
    sources:
      gp_dob:
        table_name: "PATIENT_ALF_CLEANSED"
        description: "Date of birth from gp patient table"
        priority: 1  # Higher priority = preferred source
        primary_key: "ALF_PE"
        columns:
          patient_id:
            db_column: "ALF_PE"
            data_type: "BIGINT"
          date_of_birth:
             db_column: "WOB"
             data_type: "DATE"  
          record_date:
            db_column: "CREATE_DT"
            data_type: "DATE"
      

  # =========================================================================
  # SEX ASSET
  # =========================================================================
  sex:
    description: "Patient sex/gender information"
    default_source: "gp_sex"
    
    sources:
      gp_sex:
        table_name: "PATIENT_ALF_CLEANSED"
        description: "Sex from hospital demographic records"
        priority: 1
        primary_key: "ALF_PE"
        columns:
          patient_id:
            db_column: "ALF_PE"
            data_type: "BIGINT"
          sex_code:
            db_column: "GNDR_CD"
            data_type: "CHAR(1)"
            allowed_values: ["M", "F"]
          record_date:
            db_column: "CREATE_DT"
            data_type: "DATE"
      
  # =========================================================================
  # ETHNICITY ASSET
  # =========================================================================
  ethnicity:
    description: "Patient ethnicity information"
    default_source: "self_reported_ethnicity"
    
    sources:
      # Source Table A: Hospital Admission Data
      gp_ethnicity:
        table_name: "PATIENT_ALF_CLEANSED"
        description: "Ethnicity recorded during hospital admissions"
        priority: 1
        primary_key: "ALF_PE"
        #patient_key: "ALF_PE"
        columns:
          patient_id:
            db_column: "ALF_PE"
            data_type: "BIGINT"
          ethnicity_code:
            db_column: "REG_CAT_CD"
            data_type: "CHAR(10)"
          record_date:
            db_column: "CREATE_DT"
            data_type: "DATE"
      
  # =========================================================================
  # LSOA ASSET
  # =========================================================================
  lsoa:
    description: "Lower Layer Super Output Area geographic information"
    default_source: "gp_lsoa"
    
    sources:
      # Source Table A: Current Address LSOA
      gp_lsoa:
        table_name: "PATIENT_ALF_CLEANSED"
        description: "LSOA from current patient address"
        priority: 1
        primary_key: "ALF_PE"
        
        columns:
          patient_id:
            db_column: "ALF_PE"
            data_type: "BIGINT"
          lsoa_code:
            db_column: "LSOA_CD"
            data_type: "CHAR(15)"
          record_date:
            db_column: "CREATE_DT"
            data_type: "DATE"

  # =========================================================================
  # HOSPITAL ADMISSIONS ASSET
  # =========================================================================
  hospital_admissions:
    description: "Hospital admission records with diagnoses"
    default_source: "pedw"

    sources:
      pedw:
        table_name: "PEDW_EPISODE"
        description: "Patient Episode Database for Wales (PEDW)"
        priority: 1
        data_quality: "high"
        coverage: "98%"
        primary_key: "ALF_PE"
        columns:
          patient_id:
            db_column: "ALF_PE"
            data_type: "BIGINT"
          event_date:
            db_column: "ADMIS_DT"
            data_type: "DATE"
            description: "Admission date"
          code:
            db_column: "DIAG_CD_1234"
            data_type: "VARCHAR(20)"
            description: "Primary diagnosis code"
          terminology:
            db_column: "DIAG_CD_VERSION"
            data_type: "VARCHAR(10)"
            description: "Coding system (ICD10, ICD9)"
          episode_id:
            db_column: "PROV_UNIT_CD"
            data_type: "VARCHAR(20)"

  # =========================================================================
  # PRIMARY CARE DATA ASSET
  # =========================================================================
  primary_care:
    description: "Primary care events and diagnoses"
    default_source: "wlgp"

    sources:
      wlgp:
        table_name: "GP_EVENT_REFORMATTED"
        description: "Welsh Longitudinal General Practice dataset"
        priority: 1
        data_quality: "high"
        coverage: "95%"
        primary_key: "ALF_E"
        columns:
          patient_id:
            db_column: "ALF_E"
            data_type: "BIGINT"
          event_date:
            db_column: "EVENT_DT"
            data_type: "DATE"
          code:
            db_column: "EVENT_CD_ID"
            data_type: "INT"
            description: "Read code or SNOMED code"
          event_value:
            db_column: "EVENT_VAL"
            data_type: "DECIMAL(10,2)"

  # =========================================================================
  # PRIMARY CARE MEDICINES ASSET
  # =========================================================================
  primary_care_medicines:
    description: "Primary care medicine prescriptions"
    default_source: "wlgp_medicines"

    sources:
      wlgp_medicines:
        table_name: "WLGP_MEDICATION_CLEANSED"
        description: "Welsh Longitudinal GP prescriptions"
        priority: 1
        data_quality: "high"
        coverage: "95%"
        primary_key: "ALF_PE"
        columns:
          patient_id:
            db_column: "ALF_PE"
            data_type: "BIGINT"
          event_date:
            db_column: "EVENT_DT"
            data_type: "DATE"
            description: "Prescription date"
          code:
            db_column: "BNF_CD"
            data_type: "VARCHAR(20)"
            description: "BNF code"
          terminology:
            db_column: "BNF_VERSION"
            data_type: "VARCHAR(10)"
            description: "BNF version"
          drug_name:
            db_column: "DRUG_NAME"
            data_type: "VARCHAR(200)"
          quantity:
            db_column: "QTY"
            data_type: "INTEGER"

  # =========================================================================
  # DEATHS DATA ASSET
  # =========================================================================
  deaths:
    description: "Death registrations with causes"
    default_source: "adde"

    sources:
      adde:
        table_name: "ADDE_DEATHS"
        description: "Annual District Death Extract"
        priority: 1
        data_quality: "high"
        coverage: "100%"
        primary_key: "ALF_PE"
        columns:
          patient_id:
            db_column: "ALF_PE"
            data_type: "BIGINT"
          event_date:
            db_column: "DOD"
            data_type: "DATE"
            description: "Date of death"
          code:
            db_column: "UNDERLYING_CAUSE_CD"
            data_type: "VARCHAR(20)"
            description: "Underlying cause of death"
          terminology:
            db_column: "CAUSE_CD_VERSION"
            data_type: "VARCHAR(10)"
            description: "ICD10"
          location:
            db_column: "PLACE_OF_DEATH"
            data_type: "VARCHAR(100)"

# ============================================================================
# Project Configurations
# Users can define preferred source tables for specific projects
# ============================================================================

projects:
  
  # Example Project 1: Clinical Research Study
  clinical_research_study:
    description: "Clinical research project requiring high-quality self-reported data"
    preferred_sources:
      date_of_birth: "hospital_dob"  # Use hospital DOB
      sex: "hospital_sex"             # Use hospital sex
      ethnicity: "self_reported_ethnicity"  # Prefer self-reported
      lsoa: "current_address_lsoa"    # Use current address
    fallback_strategy: "priority"  # Use priority order if preferred not available
  
  # Example Project 2: Administrative Analysis
  administrative_analysis:
    description: "Administrative analysis requiring maximum coverage"
    preferred_sources:
      date_of_birth: "registry_dob"  # Use registry for maximum coverage
      sex: "registry_sex"
      ethnicity: "admission_ethnicity"  # Use admission data for coverage
      lsoa: "gp_registration_lsoa"
    fallback_strategy: "coverage"  # Prioritize coverage over quality
  
  # Example Project 3: Health Inequalities Study
  health_inequalities:
    description: "Study focusing on deprivation and ethnicity"
    preferred_sources:
      date_of_birth: "hospital_dob"
      sex: "hospital_sex"
      ethnicity: "self_reported_ethnicity"  # Critical to use self-reported
      lsoa: "current_address_lsoa"  # Need current deprivation indices
    required_fields:
      ethnicity: ["ethnicity_category", "ethnicity_subcategory"]
      lsoa: ["imd_decile", "imd_quintile"]
    fallback_strategy: "none"  # Don't fallback - require specified sources
  
  # Example Project 4: Multi-Source Ethnicity
  ethnicity_validation:
    description: "Project comparing ethnicity across multiple sources"
    preferred_sources:
      date_of_birth: "hospital_dob"
      sex: "hospital_sex"
      ethnicity: 
        - "self_reported_ethnicity"  # Get all three sources
        - "admission_ethnicity"
        - "gp_ethnicity"
      lsoa: "current_address_lsoa"
    combine_strategy: "all"  # Retrieve from all specified sources

# ============================================================================
# Data Combination Rules
# Define how to combine data from multiple tables
# ============================================================================

combination_rules:
  
  # Strategy for combining ethnicity from multiple sources
  ethnicity:
    method: "priority_with_validation"
    steps:
      - "Use self_reported_ethnicity if available and not null"
      - "Fall back to admission_ethnicity (most recent admission)"
      - "Fall back to outpatient_ethnicity"
      - "Fall back to gp_ethnicity as last resort"
    conflict_resolution: "prefer_self_reported"
    validation:
      - "Flag if ethnicity differs across sources"
      - "Record source table used for each patient"
  
  # Strategy for combining LSOA data
  lsoa:
    method: "most_recent"
    steps:
      - "Use current_address_lsoa if record_date within last 6 months"
      - "Fall back to gp_registration_lsoa"
      - "Fall back to hospital_episode_lsoa (most recent)"
    time_window: "6 months"
    validation:
      - "Check for address changes in last 12 months"
      - "Flag if LSOA has changed"
  
  # Strategy for date of birth
  date_of_birth:
    method: "consensus"
    steps:
      - "Compare DOB across all available sources"
      - "If all agree, use agreed value"
      - "If mismatch, use highest priority source with 'EXACT' accuracy"
      - "Flag patients with DOB discrepancies"
    validation:
      - "Flag if DOB differs across sources"
      - "Flag if year differs but month/day match (transposition error)"

# ============================================================================
# Data Quality Metadata
# ============================================================================

data_quality:
  completeness:
    thresholds:
      high: 90
      medium: 70
      low: 50
  
  timeliness:
    acceptable_age_months: 6
    warning_age_months: 12
  
  validation_rules:
    date_of_birth:
      - "date_of_birth <= CURRENT_DATE"
      - "year_of_birth >= 1900"
      - "age_at_record < 120"
    sex:
      - "sex_code IN ('M', 'F', 'U', 'I')"
    ethnicity:
      - "ethnicity_code IS NOT NULL"
    lsoa:
      - "lsoa_code MATCHES '[EWNSL][0-9]{8}'"
      - "imd_decile BETWEEN 1 AND 10"
      - "imd_quintile BETWEEN 1 AND 5"

# ============================================================================
# Metadata
# ============================================================================

metadata:
  config_version: "2.0"
  created_date: "2025-10-22"
  last_updated: "2025-10-22"
  maintained_by: "Data Team"
  contact: "data-team@example.com"
  documentation_url: "https://internal-docs.example.com/data-assets"
